services:
  db:
    image: mysql:8.0
    container_name: kotona-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: kotona_db
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - ./mysql_data:/var/lib/mysql